// AUTH //
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const AUTH_LOADING = "AUTH_LOADING";
export const STOP_AUTH_LOADING = "STOP_AUTH_LOADING";
export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const GET_PROFILE = "GET_PROFILE";
export const GET_RANKING = "GET_RANKING";

// ERRORS
export const ERROR_LOADING = "ERROR_LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// IMAGE
export const DETECT_FACES = "DETECT_FACES";
export const DETECT_FACES_LOADING = "DETECT_FACES_LOADING";
export const DETECT_FACES_STOP_LOADING = "DETECT_FACES_STOP_LOADING";
